[build]
# Use all available CPU cores for compilation
jobs = -1

[alias]
merc = "run --package merc-cli --"
score = "run --package merc-cli -- bench score datasets/label.samples.json -o output/scores.json"
train = "run --package merc-cli -- bench train output/scores.json -o output/params.json"

[env]
RUST_BACKTRACE = "1"

[registries.crates-io]
protocol = "sparse"

[net]
retry = 3
